// Generated by gencpp from file ros_self_driving_car/ActuatorsCommandData.msg
// DO NOT EDIT!


#ifndef ROS_SELF_DRIVING_CAR_MESSAGE_ACTUATORSCOMMANDDATA_H
#define ROS_SELF_DRIVING_CAR_MESSAGE_ACTUATORSCOMMANDDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_self_driving_car
{
template <class ContainerAllocator>
struct ActuatorsCommandData_
{
  typedef ActuatorsCommandData_<ContainerAllocator> Type;

  ActuatorsCommandData_()
    : speed(0)
    , angle(0)  {
    }
  ActuatorsCommandData_(const ContainerAllocator& _alloc)
    : speed(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef uint32_t _speed_type;
  _speed_type speed;

   typedef uint32_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorsCommandData_

typedef ::ros_self_driving_car::ActuatorsCommandData_<std::allocator<void> > ActuatorsCommandData;

typedef boost::shared_ptr< ::ros_self_driving_car::ActuatorsCommandData > ActuatorsCommandDataPtr;
typedef boost::shared_ptr< ::ros_self_driving_car::ActuatorsCommandData const> ActuatorsCommandDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator1> & lhs, const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator1> & lhs, const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_self_driving_car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9caa6924c81cdc9852d0edbb4d6db3f1";
  }

  static const char* value(const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9caa6924c81cdc98ULL;
  static const uint64_t static_value2 = 0x52d0edbb4d6db3f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_self_driving_car/ActuatorsCommandData";
  }

  static const char* value(const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 speed\n"
"uint32 angle\n"
;
  }

  static const char* value(const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorsCommandData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_self_driving_car::ActuatorsCommandData_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SELF_DRIVING_CAR_MESSAGE_ACTUATORSCOMMANDDATA_H
