// Generated by gencpp from file ros_self_driving_car/SensorsData.msg
// DO NOT EDIT!


#ifndef ROS_SELF_DRIVING_CAR_MESSAGE_SENSORSDATA_H
#define ROS_SELF_DRIVING_CAR_MESSAGE_SENSORSDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_self_driving_car
{
template <class ContainerAllocator>
struct SensorsData_
{
  typedef SensorsData_<ContainerAllocator> Type;

  SensorsData_()
    : op_mode()
    , speed(0)
    , angle(0)
    , motor_cnt(0)
    , servo_cnt(0)  {
    }
  SensorsData_(const ContainerAllocator& _alloc)
    : op_mode(_alloc)
    , speed(0)
    , angle(0)
    , motor_cnt(0)
    , servo_cnt(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _op_mode_type;
  _op_mode_type op_mode;

   typedef uint32_t _speed_type;
  _speed_type speed;

   typedef uint32_t _angle_type;
  _angle_type angle;

   typedef uint32_t _motor_cnt_type;
  _motor_cnt_type motor_cnt;

   typedef uint32_t _servo_cnt_type;
  _servo_cnt_type servo_cnt;





  typedef boost::shared_ptr< ::ros_self_driving_car::SensorsData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_self_driving_car::SensorsData_<ContainerAllocator> const> ConstPtr;

}; // struct SensorsData_

typedef ::ros_self_driving_car::SensorsData_<std::allocator<void> > SensorsData;

typedef boost::shared_ptr< ::ros_self_driving_car::SensorsData > SensorsDataPtr;
typedef boost::shared_ptr< ::ros_self_driving_car::SensorsData const> SensorsDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_self_driving_car::SensorsData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_self_driving_car::SensorsData_<ContainerAllocator1> & lhs, const ::ros_self_driving_car::SensorsData_<ContainerAllocator2> & rhs)
{
  return lhs.op_mode == rhs.op_mode &&
    lhs.speed == rhs.speed &&
    lhs.angle == rhs.angle &&
    lhs.motor_cnt == rhs.motor_cnt &&
    lhs.servo_cnt == rhs.servo_cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_self_driving_car::SensorsData_<ContainerAllocator1> & lhs, const ::ros_self_driving_car::SensorsData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_self_driving_car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_self_driving_car::SensorsData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_self_driving_car::SensorsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_self_driving_car::SensorsData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f03b55dfb7ed838621525bc6021ad49d";
  }

  static const char* value(const ::ros_self_driving_car::SensorsData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf03b55dfb7ed8386ULL;
  static const uint64_t static_value2 = 0x21525bc6021ad49dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_self_driving_car/SensorsData";
  }

  static const char* value(const ::ros_self_driving_car::SensorsData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string op_mode\n"
"uint32 speed\n"
"uint32 angle\n"
"uint32 motor_cnt\n"
"uint32 servo_cnt\n"
;
  }

  static const char* value(const ::ros_self_driving_car::SensorsData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.op_mode);
      stream.next(m.speed);
      stream.next(m.angle);
      stream.next(m.motor_cnt);
      stream.next(m.servo_cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorsData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_self_driving_car::SensorsData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_self_driving_car::SensorsData_<ContainerAllocator>& v)
  {
    s << indent << "op_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.op_mode);
    s << indent << "speed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.angle);
    s << indent << "motor_cnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.motor_cnt);
    s << indent << "servo_cnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.servo_cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SELF_DRIVING_CAR_MESSAGE_SENSORSDATA_H
