// Generated by gencpp from file ros_self_driving_car/CalibrateDrivers.msg
// DO NOT EDIT!


#ifndef ROS_SELF_DRIVING_CAR_MESSAGE_CALIBRATEDRIVERS_H
#define ROS_SELF_DRIVING_CAR_MESSAGE_CALIBRATEDRIVERS_H

#include <ros/service_traits.h>


#include <ros_self_driving_car/CalibrateDriversRequest.h>
#include <ros_self_driving_car/CalibrateDriversResponse.h>


namespace ros_self_driving_car
{

struct CalibrateDrivers
{

typedef CalibrateDriversRequest Request;
typedef CalibrateDriversResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibrateDrivers
} // namespace ros_self_driving_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_self_driving_car::CalibrateDrivers > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_self_driving_car::CalibrateDrivers&) { return value(); }
};

template<>
struct DataType< ::ros_self_driving_car::CalibrateDrivers > {
  static const char* value()
  {
    return "ros_self_driving_car/CalibrateDrivers";
  }

  static const char* value(const ::ros_self_driving_car::CalibrateDrivers&) { return value(); }
};


// service_traits::MD5Sum< ::ros_self_driving_car::CalibrateDriversRequest> should match
// service_traits::MD5Sum< ::ros_self_driving_car::CalibrateDrivers >
template<>
struct MD5Sum< ::ros_self_driving_car::CalibrateDriversRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::CalibrateDrivers >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateDriversRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::CalibrateDriversRequest> should match
// service_traits::DataType< ::ros_self_driving_car::CalibrateDrivers >
template<>
struct DataType< ::ros_self_driving_car::CalibrateDriversRequest>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::CalibrateDrivers >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateDriversRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_self_driving_car::CalibrateDriversResponse> should match
// service_traits::MD5Sum< ::ros_self_driving_car::CalibrateDrivers >
template<>
struct MD5Sum< ::ros_self_driving_car::CalibrateDriversResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::CalibrateDrivers >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateDriversResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::CalibrateDriversResponse> should match
// service_traits::DataType< ::ros_self_driving_car::CalibrateDrivers >
template<>
struct DataType< ::ros_self_driving_car::CalibrateDriversResponse>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::CalibrateDrivers >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateDriversResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SELF_DRIVING_CAR_MESSAGE_CALIBRATEDRIVERS_H
