// Generated by gencpp from file ros_self_driving_car/Calibrate.msg
// DO NOT EDIT!


#ifndef ROS_SELF_DRIVING_CAR_MESSAGE_CALIBRATE_H
#define ROS_SELF_DRIVING_CAR_MESSAGE_CALIBRATE_H

#include <ros/service_traits.h>


#include <ros_self_driving_car/CalibrateRequest.h>
#include <ros_self_driving_car/CalibrateResponse.h>


namespace ros_self_driving_car
{

struct Calibrate
{

typedef CalibrateRequest Request;
typedef CalibrateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calibrate
} // namespace ros_self_driving_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_self_driving_car::Calibrate > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_self_driving_car::Calibrate&) { return value(); }
};

template<>
struct DataType< ::ros_self_driving_car::Calibrate > {
  static const char* value()
  {
    return "ros_self_driving_car/Calibrate";
  }

  static const char* value(const ::ros_self_driving_car::Calibrate&) { return value(); }
};


// service_traits::MD5Sum< ::ros_self_driving_car::CalibrateRequest> should match
// service_traits::MD5Sum< ::ros_self_driving_car::Calibrate >
template<>
struct MD5Sum< ::ros_self_driving_car::CalibrateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::Calibrate >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::CalibrateRequest> should match
// service_traits::DataType< ::ros_self_driving_car::Calibrate >
template<>
struct DataType< ::ros_self_driving_car::CalibrateRequest>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::Calibrate >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_self_driving_car::CalibrateResponse> should match
// service_traits::MD5Sum< ::ros_self_driving_car::Calibrate >
template<>
struct MD5Sum< ::ros_self_driving_car::CalibrateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::Calibrate >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::CalibrateResponse> should match
// service_traits::DataType< ::ros_self_driving_car::Calibrate >
template<>
struct DataType< ::ros_self_driving_car::CalibrateResponse>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::Calibrate >::value();
  }
  static const char* value(const ::ros_self_driving_car::CalibrateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SELF_DRIVING_CAR_MESSAGE_CALIBRATE_H
