// Generated by gencpp from file ros_self_driving_car/LoadCode.msg
// DO NOT EDIT!


#ifndef ROS_SELF_DRIVING_CAR_MESSAGE_LOADCODE_H
#define ROS_SELF_DRIVING_CAR_MESSAGE_LOADCODE_H

#include <ros/service_traits.h>


#include <ros_self_driving_car/LoadCodeRequest.h>
#include <ros_self_driving_car/LoadCodeResponse.h>


namespace ros_self_driving_car
{

struct LoadCode
{

typedef LoadCodeRequest Request;
typedef LoadCodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadCode
} // namespace ros_self_driving_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_self_driving_car::LoadCode > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_self_driving_car::LoadCode&) { return value(); }
};

template<>
struct DataType< ::ros_self_driving_car::LoadCode > {
  static const char* value()
  {
    return "ros_self_driving_car/LoadCode";
  }

  static const char* value(const ::ros_self_driving_car::LoadCode&) { return value(); }
};


// service_traits::MD5Sum< ::ros_self_driving_car::LoadCodeRequest> should match
// service_traits::MD5Sum< ::ros_self_driving_car::LoadCode >
template<>
struct MD5Sum< ::ros_self_driving_car::LoadCodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::LoadCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadCodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::LoadCodeRequest> should match
// service_traits::DataType< ::ros_self_driving_car::LoadCode >
template<>
struct DataType< ::ros_self_driving_car::LoadCodeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::LoadCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadCodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_self_driving_car::LoadCodeResponse> should match
// service_traits::MD5Sum< ::ros_self_driving_car::LoadCode >
template<>
struct MD5Sum< ::ros_self_driving_car::LoadCodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::LoadCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadCodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::LoadCodeResponse> should match
// service_traits::DataType< ::ros_self_driving_car::LoadCode >
template<>
struct DataType< ::ros_self_driving_car::LoadCodeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::LoadCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadCodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SELF_DRIVING_CAR_MESSAGE_LOADCODE_H
