// Generated by gencpp from file ros_self_driving_car/LoadArduinoCode.msg
// DO NOT EDIT!


#ifndef ROS_SELF_DRIVING_CAR_MESSAGE_LOADARDUINOCODE_H
#define ROS_SELF_DRIVING_CAR_MESSAGE_LOADARDUINOCODE_H

#include <ros/service_traits.h>


#include <ros_self_driving_car/LoadArduinoCodeRequest.h>
#include <ros_self_driving_car/LoadArduinoCodeResponse.h>


namespace ros_self_driving_car
{

struct LoadArduinoCode
{

typedef LoadArduinoCodeRequest Request;
typedef LoadArduinoCodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadArduinoCode
} // namespace ros_self_driving_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_self_driving_car::LoadArduinoCode > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_self_driving_car::LoadArduinoCode&) { return value(); }
};

template<>
struct DataType< ::ros_self_driving_car::LoadArduinoCode > {
  static const char* value()
  {
    return "ros_self_driving_car/LoadArduinoCode";
  }

  static const char* value(const ::ros_self_driving_car::LoadArduinoCode&) { return value(); }
};


// service_traits::MD5Sum< ::ros_self_driving_car::LoadArduinoCodeRequest> should match
// service_traits::MD5Sum< ::ros_self_driving_car::LoadArduinoCode >
template<>
struct MD5Sum< ::ros_self_driving_car::LoadArduinoCodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::LoadArduinoCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadArduinoCodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::LoadArduinoCodeRequest> should match
// service_traits::DataType< ::ros_self_driving_car::LoadArduinoCode >
template<>
struct DataType< ::ros_self_driving_car::LoadArduinoCodeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::LoadArduinoCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadArduinoCodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_self_driving_car::LoadArduinoCodeResponse> should match
// service_traits::MD5Sum< ::ros_self_driving_car::LoadArduinoCode >
template<>
struct MD5Sum< ::ros_self_driving_car::LoadArduinoCodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_self_driving_car::LoadArduinoCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadArduinoCodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_self_driving_car::LoadArduinoCodeResponse> should match
// service_traits::DataType< ::ros_self_driving_car::LoadArduinoCode >
template<>
struct DataType< ::ros_self_driving_car::LoadArduinoCodeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_self_driving_car::LoadArduinoCode >::value();
  }
  static const char* value(const ::ros_self_driving_car::LoadArduinoCodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SELF_DRIVING_CAR_MESSAGE_LOADARDUINOCODE_H
