# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_self_driving_car/SensorsData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SensorsData(genpy.Message):
  _md5sum = "ca5a2621c8a00e6fea801ce1abd88ec5"
  _type = "ros_self_driving_car/SensorsData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string op_mode
int32 speed
int32 angle
uint32 motor_cnt
uint32 servo_cnt
bool wheel_1_success
bool wheel_2_success
bool wheel_3_success
bool wheel_4_success
"""
  __slots__ = ['op_mode','speed','angle','motor_cnt','servo_cnt','wheel_1_success','wheel_2_success','wheel_3_success','wheel_4_success']
  _slot_types = ['string','int32','int32','uint32','uint32','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       op_mode,speed,angle,motor_cnt,servo_cnt,wheel_1_success,wheel_2_success,wheel_3_success,wheel_4_success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorsData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.op_mode is None:
        self.op_mode = ''
      if self.speed is None:
        self.speed = 0
      if self.angle is None:
        self.angle = 0
      if self.motor_cnt is None:
        self.motor_cnt = 0
      if self.servo_cnt is None:
        self.servo_cnt = 0
      if self.wheel_1_success is None:
        self.wheel_1_success = False
      if self.wheel_2_success is None:
        self.wheel_2_success = False
      if self.wheel_3_success is None:
        self.wheel_3_success = False
      if self.wheel_4_success is None:
        self.wheel_4_success = False
    else:
      self.op_mode = ''
      self.speed = 0
      self.angle = 0
      self.motor_cnt = 0
      self.servo_cnt = 0
      self.wheel_1_success = False
      self.wheel_2_success = False
      self.wheel_3_success = False
      self.wheel_4_success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.op_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i2I4B().pack(_x.speed, _x.angle, _x.motor_cnt, _x.servo_cnt, _x.wheel_1_success, _x.wheel_2_success, _x.wheel_3_success, _x.wheel_4_success))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.op_mode = str[start:end].decode('utf-8')
      else:
        self.op_mode = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.speed, _x.angle, _x.motor_cnt, _x.servo_cnt, _x.wheel_1_success, _x.wheel_2_success, _x.wheel_3_success, _x.wheel_4_success,) = _get_struct_2i2I4B().unpack(str[start:end])
      self.wheel_1_success = bool(self.wheel_1_success)
      self.wheel_2_success = bool(self.wheel_2_success)
      self.wheel_3_success = bool(self.wheel_3_success)
      self.wheel_4_success = bool(self.wheel_4_success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.op_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i2I4B().pack(_x.speed, _x.angle, _x.motor_cnt, _x.servo_cnt, _x.wheel_1_success, _x.wheel_2_success, _x.wheel_3_success, _x.wheel_4_success))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.op_mode = str[start:end].decode('utf-8')
      else:
        self.op_mode = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.speed, _x.angle, _x.motor_cnt, _x.servo_cnt, _x.wheel_1_success, _x.wheel_2_success, _x.wheel_3_success, _x.wheel_4_success,) = _get_struct_2i2I4B().unpack(str[start:end])
      self.wheel_1_success = bool(self.wheel_1_success)
      self.wheel_2_success = bool(self.wheel_2_success)
      self.wheel_3_success = bool(self.wheel_3_success)
      self.wheel_4_success = bool(self.wheel_4_success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i2I4B = None
def _get_struct_2i2I4B():
    global _struct_2i2I4B
    if _struct_2i2I4B is None:
        _struct_2i2I4B = struct.Struct("<2i2I4B")
    return _struct_2i2I4B
